import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";
import ClientLayoutWrapper from "./ClientLayoutWrapper";
import { cookies } from "next/headers";
import { AuthProvider } from "@/lib/auth-context";
import Providers from "./providers";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token");



  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={geistMono.variable}>
        <Providers>
          <AuthProvider token={token?.value || null} >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
            </ThemeProvider>
          </AuthProvider>
        </Providers>

      </body>
    </html>
  );
}
